vocab:
  type: Vocab
  path:
    train: ../../../data/clean_data/train.json
    dev: ../../../data/clean_data/dev.json
    test: ../../../data/clean_data/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train:
    type: SentimentDataset
    path: ../../../data/clean_data/train.json
  dev:
    type: SentimentDataset
    path: ../../../data/clean_data/dev.json
  test:
    type: SentimentDataset
    path: ../../../data/clean_data/test.json
  batch_size: 32
  num_workers: 16

model:
  name: LSTM_Model3layer_Wikilingual
  architecture: LSTM
  embed_dim: 300
  hidden_dim: 128
  polarities_dim: 20  
  num_layers: 3
  bidirectional: false
  dropout: 0.1
  device: cpu

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.5
  warmup: 100
  patience: 5
  batch_size: 32
  max_seq_len: 256
  score: accuracy

task: SentimentAnalysisTask